### ISSUE TITLE
我喜欢你的前言：“我的HTTPS学习之旅”

### ISSUE THREAD

**Issue by JserJser** [ywdblog/httpsbook#13]
友情链接让人受益颇多，那些尘封在时间里的程序员，写在博客里面。向那些敬业热爱技术的程序员学习。

**Comment by ywdblog** [comment]
感谢支持，欢迎在[豆瓣](https://book.douban.com/subject/30250772/)为本书做个评论，以便让更多人了解这本书，谢谢~
