### ISSUE TITLE
没有示例代码？

### ISSUE THREAD

**Issue by Jiangxumin** [ywdblog/httpsbook#4]
# 书已在京东购买。

*  www.simplehttps.com 无法访问。
*  本git仓储没找到示例代码。

**Comment by Jiangxumin** [comment]
* http://www.simplehttps.com  能访问？
* https://www.simplehttps.com 无法访问？

**Comment by ywdblog** [comment]
抱歉，示例代码我最近在更新。

**Comment by ywdblog** [comment]
@Jiangxumin  https://www.simplehttps.com  是我当时假设关于 HTTPS 方面的一个网站，现在内容很少。为了让大家体验到最新 TLS 1.3 协议，这个网站支持 TLS 1.3 (TLS 1.2也不支持)，需要升级你的浏览器（比如 chrome 需要69以上版本）才能访问，你可以试下。

有其他建议或问题，可以随时提出。

**Comment by ywdblog** [comment]
已经更新了大部分示例
